version: '3.8'
services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./app/src
        target: /var/www/html
      - type: bind
        source: ./app/php.ini
        target: /usr/local/etc/php/php.ini
    environment:
      - MYSQL_HOST=database
      - MYSQL_DATABASE=contactdb
      - MYSQL_USER=client
      - MYSQL_PASSWORD=Cha171205
  database:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - type: volume
        source: contactdb
        target: /var/lib/mysql
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD=ImGroot3301*$
      - MYSQL_DATABASE=contactdb
      - MYSQL_USER=client
      - MYSQL_PASSWORD=Cha171205
volumes:
  contactdb: