-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 16:22:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- PHP access to the database : User privileges
-- -----------------------------------------------------
REVOKE ALL PRIVILEGES ON contactdb.* FROM 'client'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON contactdb.* TO 'client'@'%';
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Schema contactdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contactdb` DEFAULT CHARACTER SET utf8 ;
USE `contactdb` ;

-- -----------------------------------------------------
-- Table `contactdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contactdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `firstname` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `signup_date` DATETIME NOT NULL,
  `token` VARCHAR(70) NOT NULL,
  `tokie_time` VARCHAR(70),
  PRIMARY KEY (`id`),
  UNIQUE KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contactdb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contactdb`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `firstname` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `user_email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `contactdb`.`pw_reset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contactdb`.`pw_reset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(70) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `expiracy` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
